# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

github: [marcofortina]
custom:
  - "https://paypal.me/marcofortina"
  - "https://www.blockchain.com/explorer/addresses/btc/36jDV57roGb4o59TwK1CB7viPrXToQHGiP"
