# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

if(NOT DEFINED OPENSSL_INCLUDE_DIR AND DEFINED ENV{OPENSSL_INCLUDE_DIR})
    set(OPENSSL_INCLUDE_DIR "$ENV{OPENSSL_INCLUDE_DIR}" CACHE PATH "OpenSSL include directory")
endif()
find_package(OpenSSL 3.0 CONFIG QUIET)
if(NOT OpenSSL_FOUND)
    find_package(OpenSSL 3.0 REQUIRED)
endif()
find_package(Iconv REQUIRED)
find_package(Doxygen QUIET)
find_package(PkgConfig QUIET)
find_package(Threads REQUIRED)

set(LIBRDP_ICONV_LINK_LIBRARIES Iconv::Iconv)
find_library(LIBRDP_ICONV_EXTRA_LIBRARY NAMES iconv)
if(LIBRDP_ICONV_EXTRA_LIBRARY)
    list(APPEND LIBRDP_ICONV_LINK_LIBRARIES ${LIBRDP_ICONV_EXTRA_LIBRARY})
endif()
set(LIBRDP_ICONV_INCLUDE_DIRECTORIES)
foreach(include_dir IN LISTS Iconv_INCLUDE_DIRS)
    if(include_dir AND EXISTS "${include_dir}/iconv.h")
        list(APPEND LIBRDP_ICONV_INCLUDE_DIRECTORIES "${include_dir}")
    endif()
endforeach()
if(Iconv_INCLUDE_DIR AND EXISTS "${Iconv_INCLUDE_DIR}/iconv.h")
    list(APPEND LIBRDP_ICONV_INCLUDE_DIRECTORIES "${Iconv_INCLUDE_DIR}")
endif()
if(LIBRDP_ICONV_INCLUDE_DIRECTORIES)
    list(REMOVE_DUPLICATES LIBRDP_ICONV_INCLUDE_DIRECTORIES)
endif()

function(librdp_apply_iconv_include_dirs target)
    if(LIBRDP_ICONV_INCLUDE_DIRECTORIES)
        target_include_directories(${target} SYSTEM PRIVATE ${LIBRDP_ICONV_INCLUDE_DIRECTORIES})
    endif()
endfunction()

set(LIBRDP_OPENSSL_INCLUDE_DIRECTORIES)
if(LIBRDP_OPENSSL_INCLUDE_DIR AND EXISTS "${LIBRDP_OPENSSL_INCLUDE_DIR}/openssl/types.h")
    list(APPEND LIBRDP_OPENSSL_INCLUDE_DIRECTORIES "${LIBRDP_OPENSSL_INCLUDE_DIR}")
endif()
foreach(var OPENSSL_INCLUDE_DIR OpenSSL_INCLUDE_DIR OPENSSL_INCLUDE_DIRS OpenSSL_INCLUDE_DIRS)
    if(DEFINED ${var})
        foreach(include_dir IN LISTS ${var})
            if(include_dir AND EXISTS "${include_dir}/openssl/types.h")
                list(APPEND LIBRDP_OPENSSL_INCLUDE_DIRECTORIES "${include_dir}")
            endif()
        endforeach()
    endif()
endforeach()
if(LIBRDP_OPENSSL_INCLUDE_DIRECTORIES)
    list(REMOVE_DUPLICATES LIBRDP_OPENSSL_INCLUDE_DIRECTORIES)
endif()

function(librdp_apply_openssl_include_dirs target)
    if(LIBRDP_OPENSSL_INCLUDE_DIRECTORIES)
        target_include_directories(${target} SYSTEM PRIVATE ${LIBRDP_OPENSSL_INCLUDE_DIRECTORIES})
    endif()
endfunction()

librdp_pkg_dependency(LIBRDP_WITH_FFMPEG_AVC LIBRDP_FFMPEG_AVC libavcodec libavutil libswscale)
librdp_pkg_dependency(LIBRDP_WITH_OPENH264_AVC LIBRDP_OPENH264_AVC openh264)
librdp_pkg_dependency(LIBRDP_WITH_PCSC LIBRDP_PCSC libpcsclite)
librdp_pkg_dependency(LIBRDP_WITH_LIBUSB LIBRDP_LIBUSB libusb-1.0)
librdp_pkg_dependency(LIBRDP_WITH_FIDO2 LIBRDP_FIDO2 libfido2)
librdp_pkg_dependency(LIBRDP_WITH_CBOR LIBRDP_CBOR libcbor)
librdp_pkg_dependency(LIBRDP_WITH_ACL LIBRDP_ACL libacl)
librdp_pkg_dependency(LIBRDP_WITH_ATTR LIBRDP_ATTR libattr)
librdp_pkg_dependency(LIBRDP_WITH_ARCHIVE LIBRDP_ARCHIVE libarchive)
librdp_pkg_dependency(LIBRDP_WITH_PIPEWIRE LIBRDP_PIPEWIRE libpipewire-0.3)
librdp_pkg_dependency(LIBRDP_WITH_JPEG LIBRDP_JPEG libjpeg)

function(librdp_real_library_path input output)
    if(input AND EXISTS "${input}")
        get_filename_component(resolved "${input}" REALPATH)
    else()
        set(resolved "${input}")
    endif()
    set(${output} "${resolved}" PARENT_SCOPE)
endfunction()

function(librdp_fido2_reject_if_crypto_mismatch dependency)
    if(NOT LIBRDP_FIDO2_FOUND OR NOT OPENSSL_CRYPTO_LIBRARY OR NOT dependency)
        return()
    endif()
    librdp_real_library_path("${OPENSSL_CRYPTO_LIBRARY}" openssl_crypto)
    librdp_real_library_path("${dependency}" fido2_crypto)
    get_filename_component(openssl_crypto_name "${openssl_crypto}" NAME)
    get_filename_component(fido2_crypto_name "${fido2_crypto}" NAME)
    if(NOT fido2_crypto STREQUAL openssl_crypto AND NOT fido2_crypto_name STREQUAL openssl_crypto_name)
        if("${LIBRDP_WITH_FIDO2}" STREQUAL "ON")
            message(FATAL_ERROR "LIBRDP_WITH_FIDO2=ON requires libfido2 to use the selected OpenSSL libcrypto")
        endif()
        message(STATUS "librdp disabling FIDO2: libfido2 uses ${fido2_crypto_name}, selected OpenSSL uses ${openssl_crypto_name}")
        set(LIBRDP_FIDO2_FOUND 0 PARENT_SCOPE)
        set(LIBRDP_FIDO2_FOUND_REASON incompatible-openssl-crypto PARENT_SCOPE)
    endif()
endfunction()

if(LIBRDP_FIDO2_FOUND)
    if(DEFINED pkgcfg_lib_LIBRDP_FIDO2_crypto)
        librdp_fido2_reject_if_crypto_mismatch("${pkgcfg_lib_LIBRDP_FIDO2_crypto}")
    endif()
    if(LIBRDP_FIDO2_FOUND AND DEFINED pkgcfg_lib_LIBRDP_FIDO2_fido2)
        find_program(LIBRDP_LDD_EXECUTABLE NAMES ldd)
        if(LIBRDP_LDD_EXECUTABLE)
            execute_process(
                COMMAND "${LIBRDP_LDD_EXECUTABLE}" "${pkgcfg_lib_LIBRDP_FIDO2_fido2}"
                RESULT_VARIABLE LIBRDP_FIDO2_LDD_RESULT
                OUTPUT_VARIABLE LIBRDP_FIDO2_LDD_OUTPUT
                ERROR_VARIABLE LIBRDP_FIDO2_LDD_ERROR
            )
            if(LIBRDP_FIDO2_LDD_RESULT EQUAL 0)
                string(REGEX MATCH "(/[^ \t\r\n]*libcrypto[^ \t\r\n]*|libcrypto\\.so\\.[^ \t\r\n]+)"
                    LIBRDP_FIDO2_CRYPTO_DEPENDENCY "${LIBRDP_FIDO2_LDD_OUTPUT}")
                if(LIBRDP_FIDO2_CRYPTO_DEPENDENCY)
                    librdp_fido2_reject_if_crypto_mismatch("${LIBRDP_FIDO2_CRYPTO_DEPENDENCY}")
                endif()
            endif()
        endif()
    endif()
endif()

set(LIBRDP_CUPS_FOUND 0)
if(NOT "${LIBRDP_WITH_CUPS}" STREQUAL "OFF")
    if(PkgConfig_FOUND)
        pkg_check_modules(LIBRDP_CUPS QUIET IMPORTED_TARGET cups)
    endif()
endif()

set(LIBRDP_XSHM_FOUND 0 CACHE INTERNAL "MIT-SHM support found for the X11 viewer" FORCE)
set(LIBRDP_XRANDR_FOUND 0 CACHE INTERNAL "XRandR support found for the X11 viewer" FORCE)

if(NOT LIBRDP_CUPS_FOUND AND NOT "${LIBRDP_WITH_CUPS}" STREQUAL "OFF")
    find_path(LIBRDP_CUPS_INCLUDE_DIR NAMES cups/cups.h PATHS
        /usr/local/include
        /usr/include
        /opt/local/include
    )
    find_library(LIBRDP_CUPS_LIBRARY NAMES cups PATHS
        /usr/local/lib
        /usr/lib
        /usr/lib/${CMAKE_LIBRARY_ARCHITECTURE}
        /opt/local/lib
    )
    if(LIBRDP_CUPS_INCLUDE_DIR AND LIBRDP_CUPS_LIBRARY)
        set(LIBRDP_CUPS_FOUND 1)
    endif()
endif()
if("${LIBRDP_WITH_CUPS}" STREQUAL "ON" AND NOT LIBRDP_CUPS_FOUND)
    message(FATAL_ERROR "LIBRDP_WITH_CUPS=ON requires cups")
endif()
function(librdp_cups_reject_if_crypto_mismatch dependency)
    if(NOT LIBRDP_CUPS_FOUND OR NOT OPENSSL_CRYPTO_LIBRARY OR NOT dependency)
        return()
    endif()
    librdp_real_library_path("${OPENSSL_CRYPTO_LIBRARY}" openssl_crypto)
    librdp_real_library_path("${dependency}" cups_crypto)
    get_filename_component(openssl_crypto_name "${openssl_crypto}" NAME)
    get_filename_component(cups_crypto_name "${cups_crypto}" NAME)
    if(NOT cups_crypto STREQUAL openssl_crypto AND NOT cups_crypto_name STREQUAL openssl_crypto_name)
        if("${LIBRDP_WITH_CUPS}" STREQUAL "ON")
            message(FATAL_ERROR "LIBRDP_WITH_CUPS=ON requires cups to use the selected OpenSSL libcrypto")
        endif()
        message(STATUS "librdp disabling CUPS: cups uses ${cups_crypto_name}, selected OpenSSL uses ${openssl_crypto_name}")
        set(LIBRDP_CUPS_FOUND 0 PARENT_SCOPE)
        set(LIBRDP_CUPS_FOUND_REASON incompatible-openssl-crypto PARENT_SCOPE)
    endif()
endfunction()

function(librdp_cups_reject_if_ldd_crypto_mismatch library)
    if(NOT LIBRDP_CUPS_FOUND OR NOT library)
        return()
    endif()
    find_program(LIBRDP_LDD_EXECUTABLE NAMES ldd)
    if(NOT LIBRDP_LDD_EXECUTABLE)
        return()
    endif()
    execute_process(
        COMMAND "${LIBRDP_LDD_EXECUTABLE}" "${library}"
        RESULT_VARIABLE LIBRDP_CUPS_LDD_RESULT
        OUTPUT_VARIABLE LIBRDP_CUPS_LDD_OUTPUT
        ERROR_VARIABLE LIBRDP_CUPS_LDD_ERROR
    )
    if(LIBRDP_CUPS_LDD_RESULT EQUAL 0)
        string(REGEX MATCH "(/[^ \t\r\n]*libcrypto[^ \t\r\n]*|libcrypto\\.so\\.[^ \t\r\n]+)"
            LIBRDP_CUPS_CRYPTO_DEPENDENCY "${LIBRDP_CUPS_LDD_OUTPUT}")
        if(LIBRDP_CUPS_CRYPTO_DEPENDENCY)
            librdp_cups_reject_if_crypto_mismatch("${LIBRDP_CUPS_CRYPTO_DEPENDENCY}")
            if(NOT LIBRDP_CUPS_FOUND)
                set(LIBRDP_CUPS_FOUND 0 PARENT_SCOPE)
                set(LIBRDP_CUPS_FOUND_REASON "${LIBRDP_CUPS_FOUND_REASON}" PARENT_SCOPE)
            endif()
        endif()
    endif()
endfunction()

if(LIBRDP_CUPS_FOUND)
    if(DEFINED pkgcfg_lib_LIBRDP_CUPS_cups)
        librdp_cups_reject_if_ldd_crypto_mismatch("${pkgcfg_lib_LIBRDP_CUPS_cups}")
    elseif(LIBRDP_CUPS_LIBRARY)
        librdp_cups_reject_if_ldd_crypto_mismatch("${LIBRDP_CUPS_LIBRARY}")
    endif()
endif()
set(LIBRDP_CUPS_USES_PKG_CONFIG 0)
if(LIBRDP_CUPS_FOUND AND TARGET PkgConfig::LIBRDP_CUPS)
    set(LIBRDP_CUPS_USES_PKG_CONFIG 1)
endif()

function(librdp_apply_x11_camera_backends target)
    if(LIBRDP_JPEG_FOUND)
        target_compile_definitions(${target} PRIVATE LIBRDP_HAVE_JPEG=1)
        target_link_libraries(${target} PRIVATE PkgConfig::LIBRDP_JPEG)
    endif()
endfunction()

function(librdp_apply_x11_device_backends target)
    if(LIBRDP_LIBUSB_FOUND)
        target_compile_definitions(${target} PRIVATE LIBRDP_HAVE_LIBUSB=1)
        target_link_libraries(${target} PRIVATE PkgConfig::LIBRDP_LIBUSB)
    endif()
    if(LIBRDP_PCSC_FOUND)
        target_compile_definitions(${target} PRIVATE LIBRDP_HAVE_PCSC=1)
        target_link_libraries(${target} PRIVATE PkgConfig::LIBRDP_PCSC)
    endif()
    if(LIBRDP_FIDO2_FOUND)
        target_compile_definitions(${target} PRIVATE LIBRDP_HAVE_FIDO2=1)
        target_link_libraries(${target} PRIVATE PkgConfig::LIBRDP_FIDO2)
    endif()
endfunction()
