# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

if(LIBRDP_BUILD_FUZZ)
    function(add_librdp_fuzzer name source)
        add_executable(${name} ${source})
        target_include_directories(${name} PRIVATE
            ${CMAKE_CURRENT_SOURCE_DIR}/include
            ${CMAKE_CURRENT_SOURCE_DIR}/src
        )
        librdp_link_internal_runtime(${name})
        librdp_apply_warning_options(${name})
        if(LIBRDP_FFMPEG_AVC_FOUND)
            target_compile_definitions(${name} PRIVATE RDP_HAVE_FFMPEG_AVC=1)
        endif()
        if(LIBRDP_OPENH264_AVC_FOUND)
            target_compile_definitions(${name} PRIVATE RDP_HAVE_OPENH264_AVC=1)
        endif()
        set(librdp_fuzzer_uses_libfuzzer 0)
        if(CMAKE_C_COMPILER_ID MATCHES "Clang")
            set(librdp_fuzzer_uses_libfuzzer 1)
            set(fuzzer_sanitizers fuzzer)
            if(LIBRDP_ENABLE_SANITIZERS)
                list(APPEND fuzzer_sanitizers ${LIBRDP_SANITIZER_FLAGS})
            else()
                list(APPEND fuzzer_sanitizers address undefined)
            endif()
            list(REMOVE_DUPLICATES fuzzer_sanitizers)
            list(JOIN fuzzer_sanitizers "," fuzzer_sanitizer_value)
            target_compile_options(${name} PRIVATE -fsanitize=${fuzzer_sanitizer_value})
            target_link_options(${name} PRIVATE -fsanitize=${fuzzer_sanitizer_value})
        else()
            target_sources(${name} PRIVATE fuzz/fuzz_main.c)
            librdp_apply_sanitizer_compile_options(${name})
            librdp_apply_sanitizer_link_options(${name})
        endif()
        add_test(NAME ${name}_seed_smoke
            COMMAND ${CMAKE_COMMAND}
                "-DLIBRDP_SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR}"
                "-DLIBRDP_FUZZ_TARGET=${name}"
                "-DLIBRDP_FUZZ_EXECUTABLE=$<TARGET_FILE:${name}>"
                "-DLIBRDP_FUZZ_USES_LIBFUZZER=${librdp_fuzzer_uses_libfuzzer}"
                -P ${CMAKE_CURRENT_SOURCE_DIR}/tests/fuzz_seed_smoke.cmake)
        set_tests_properties(${name}_seed_smoke PROPERTIES TIMEOUT 20)
    endfunction()

    add_librdp_fuzzer(fuzz_x224 fuzz/x224_fuzzer.c)
    add_librdp_fuzzer(fuzz_stream fuzz/stream_fuzzer.c)
    add_librdp_fuzzer(fuzz_charset fuzz/charset_fuzzer.c)
    add_librdp_fuzzer(fuzz_session_selection fuzz/session_selection_fuzzer.c)
    add_librdp_fuzzer(fuzz_mcs fuzz/mcs_fuzzer.c)
    add_librdp_fuzzer(fuzz_pointer fuzz/pointer_fuzzer.c)
    add_librdp_fuzzer(fuzz_gcc fuzz/gcc_fuzzer.c)
    add_librdp_fuzzer(fuzz_capabilities fuzz/capabilities_fuzzer.c)
    add_librdp_fuzzer(fuzz_fastpath fuzz/fastpath_fuzzer.c)
    add_librdp_fuzzer(fuzz_slowpath fuzz/slowpath_fuzzer.c)
    add_librdp_fuzzer(fuzz_tpkt fuzz/tpkt_fuzzer.c)
    add_librdp_fuzzer(fuzz_bulk fuzz/bulk_fuzzer.c)
    add_librdp_fuzzer(fuzz_bitmap fuzz/bitmap_fuzzer.c)
    add_librdp_fuzzer(fuzz_virtual_channel fuzz/virtual_channel_fuzzer.c)
    add_librdp_fuzzer(fuzz_dynamic_channel fuzz/dynamic_channel_fuzzer.c)
    add_librdp_fuzzer(fuzz_echo_channel fuzz/echo_channel_fuzzer.c)
    add_librdp_fuzzer(fuzz_audio_format fuzz/audio_format_fuzzer.c)
    add_librdp_fuzzer(fuzz_audio_output fuzz/audio_output_fuzzer.c)
    add_librdp_fuzzer(fuzz_audio_input fuzz/audio_input_fuzzer.c)
    add_librdp_fuzzer(fuzz_composited_remoting fuzz/composited_remoting_fuzzer.c)
    add_librdp_fuzzer(fuzz_display_control fuzz/display_control_fuzzer.c)
    add_librdp_fuzzer(fuzz_device_redirection fuzz/device_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_desktop_composition fuzz/desktop_composition_fuzzer.c)
    add_librdp_fuzzer(fuzz_filesystem_redirection fuzz/filesystem_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_port_redirection fuzz/port_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_printer_redirection fuzz/printer_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_remote_programs fuzz/remote_programs_fuzzer.c)
    add_librdp_fuzzer(fuzz_pnp_redirection fuzz/pnp_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_usb_redirection fuzz/usb_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_core_input fuzz/core_input_fuzzer.c)
    add_librdp_fuzzer(fuzz_input_channel fuzz/input_channel_fuzzer.c)
    add_librdp_fuzzer(fuzz_graphics_pipeline fuzz/graphics_pipeline_fuzzer.c)
    add_librdp_fuzzer(fuzz_avc fuzz/avc_fuzzer.c)
    add_librdp_fuzzer(fuzz_mouse_cursor fuzz/mouse_cursor_fuzzer.c)
    add_librdp_fuzzer(fuzz_multiparty fuzz/multiparty_fuzzer.c)
    add_librdp_fuzzer(fuzz_telemetry fuzz/telemetry_fuzzer.c)
    add_librdp_fuzzer(fuzz_clearcodec fuzz/clearcodec_fuzzer.c)
    add_librdp_fuzzer(fuzz_nscodec fuzz/nscodec_fuzzer.c)
    add_librdp_fuzzer(fuzz_planar fuzz/planar_fuzzer.c)
    add_librdp_fuzzer(fuzz_rfx_codec fuzz/rfx_codec_fuzzer.c)
    add_librdp_fuzzer(fuzz_rfx_stream fuzz/rfx_stream_fuzzer.c)
    add_librdp_fuzzer(fuzz_surface_commands fuzz/surface_commands_fuzzer.c)
    add_librdp_fuzzer(fuzz_clipboard fuzz/clipboard_fuzzer.c)
    add_librdp_fuzzer(fuzz_security fuzz/security_fuzzer.c)
    add_librdp_fuzzer(fuzz_licensing fuzz/licensing_fuzzer.c)
    add_librdp_fuzzer(fuzz_credssp fuzz/credssp_fuzzer.c)
    add_librdp_fuzzer(fuzz_udp_transport fuzz/udp_transport_fuzzer.c)
    add_librdp_fuzzer(fuzz_multitransport fuzz/multitransport_fuzzer.c)
    add_librdp_fuzzer(fuzz_xps_print fuzz/xps_print_fuzzer.c)
    add_librdp_fuzzer(fuzz_auth_redirection fuzz/auth_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_smartcard_redirection fuzz/smartcard_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_video_capture fuzz/video_capture_fuzzer.c)
    add_librdp_fuzzer(fuzz_video_redirection fuzz/video_redirection_fuzzer.c)
    add_librdp_fuzzer(fuzz_video_optimized fuzz/video_optimized_fuzzer.c)
    add_librdp_fuzzer(fuzz_gdi_orders fuzz/gdi_orders_fuzzer.c)
    add_librdp_fuzzer(fuzz_webauthn_channel fuzz/webauthn_channel_fuzzer.c)
endif()
