# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

set(LIBRDP_ABI_VERSION 0 CACHE STRING "Shared-library ABI version")
set(LIBRDP_LIBRARY_TYPE "AUTO" CACHE STRING "Library type to build (AUTO, STATIC, SHARED, BOTH)")
set(LIBRDP_OPENSSL_INCLUDE_DIR "" CACHE PATH "Additional OpenSSL include directory for platform package layouts")
set_property(CACHE LIBRDP_LIBRARY_TYPE PROPERTY STRINGS AUTO STATIC SHARED BOTH)
string(TOUPPER "${LIBRDP_LIBRARY_TYPE}" LIBRDP_LIBRARY_TYPE)
set(LIBRDP_LIBRARY_TYPE "${LIBRDP_LIBRARY_TYPE}" CACHE STRING "Library type to build (AUTO, STATIC, SHARED, BOTH)" FORCE)
if(NOT LIBRDP_LIBRARY_TYPE MATCHES "^(AUTO|STATIC|SHARED|BOTH)$")
    message(FATAL_ERROR "LIBRDP_LIBRARY_TYPE must be AUTO, STATIC, SHARED, or BOTH")
endif()

option(LIBRDP_BUILD_TESTS "Build unit tests" ON)
option(LIBRDP_BUILD_FUZZ "Build fuzz targets" OFF)
option(LIBRDP_BUILD_X11_VIEWER "Build X11 viewer" OFF)
option(LIBRDP_BUILD_COCOA_VIEWER "Build native Cocoa viewer" OFF)
option(LIBRDP_BUILD_X11_ADMIN "Build X11 administration inventory tool" OFF)
option(LIBRDP_BUILD_X11_WORKSPACE "Build X11 workspace feed launcher" OFF)
option(LIBRDP_BUILD_COCOA_ADMIN "Build native Cocoa administration inventory tool" OFF)
option(LIBRDP_BUILD_COCOA_WORKSPACE "Build native Cocoa workspace feed launcher" OFF)
option(LIBRDP_BUILD_EXAMPLES "Build example programs" ON)
option(LIBRDP_ENABLE_WERROR "Treat project compiler warnings as errors" OFF)
option(LIBRDP_ENABLE_SANITIZERS "Enable selected compiler sanitizers on project targets" OFF)
set(LIBRDP_SANITIZERS "address;undefined" CACHE STRING "Sanitizers enabled when LIBRDP_ENABLE_SANITIZERS is ON")

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

function(librdp_check_sanitizer_support flag result_var)
    set(saved_required_flags "")
    set(saved_required_link_options "")
    if(DEFINED CMAKE_REQUIRED_FLAGS)
        set(saved_required_flags "${CMAKE_REQUIRED_FLAGS}")
    endif()
    if(DEFINED CMAKE_REQUIRED_LINK_OPTIONS)
        set(saved_required_link_options "${CMAKE_REQUIRED_LINK_OPTIONS}")
    endif()
    if(saved_required_flags)
        set(CMAKE_REQUIRED_FLAGS "${saved_required_flags} ${flag}")
    else()
        set(CMAKE_REQUIRED_FLAGS "${flag}")
    endif()
    list(APPEND CMAKE_REQUIRED_LINK_OPTIONS "${flag}")
    check_c_source_compiles("int main(void) { return 0; }" ${result_var})
    set(CMAKE_REQUIRED_FLAGS "${saved_required_flags}")
    set(CMAKE_REQUIRED_LINK_OPTIONS "${saved_required_link_options}")
endfunction()

set(LIBRDP_SANITIZER_FLAG_VALUE "")
if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
    librdp_check_sanitizer_support("-fsanitize=address" LIBRDP_SANITIZER_ADDRESS_LINKS)
    librdp_check_sanitizer_support("-fsanitize=undefined" LIBRDP_SANITIZER_UNDEFINED_LINKS)
else()
    set(LIBRDP_SANITIZER_ADDRESS_LINKS 0)
    set(LIBRDP_SANITIZER_UNDEFINED_LINKS 0)
endif()
if(LIBRDP_ENABLE_SANITIZERS)
    if(NOT CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        message(FATAL_ERROR "LIBRDP_ENABLE_SANITIZERS requires GCC or Clang")
    endif()
    string(REPLACE "," ";" LIBRDP_SANITIZER_LIST "${LIBRDP_SANITIZERS}")
    set(LIBRDP_SANITIZER_FLAGS "")
    foreach(sanitizer IN LISTS LIBRDP_SANITIZER_LIST)
        string(TOLOWER "${sanitizer}" sanitizer_name)
        if(NOT sanitizer_name MATCHES "^(address|undefined)$")
            message(FATAL_ERROR "LIBRDP_SANITIZERS entries must be address or undefined")
        endif()
        if(sanitizer_name STREQUAL "address" AND NOT LIBRDP_SANITIZER_ADDRESS_LINKS)
            message(FATAL_ERROR "address sanitizer is not supported by this compiler")
        endif()
        if(sanitizer_name STREQUAL "undefined" AND NOT LIBRDP_SANITIZER_UNDEFINED_LINKS)
            message(FATAL_ERROR "undefined sanitizer is not supported by this compiler")
        endif()
        list(APPEND LIBRDP_SANITIZER_FLAGS "${sanitizer_name}")
    endforeach()
    list(REMOVE_DUPLICATES LIBRDP_SANITIZER_FLAGS)
    if(NOT LIBRDP_SANITIZER_FLAGS)
        message(FATAL_ERROR "LIBRDP_ENABLE_SANITIZERS requires at least one sanitizer")
    endif()
    list(JOIN LIBRDP_SANITIZER_FLAGS "," LIBRDP_SANITIZER_FLAG_VALUE)
endif()

set(LIBRDP_SYSTEM_COMPILE_DEFINITIONS)
if(APPLE)
    list(APPEND LIBRDP_SYSTEM_COMPILE_DEFINITIONS _DARWIN_C_SOURCE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    list(APPEND LIBRDP_SYSTEM_COMPILE_DEFINITIONS _NETBSD_SOURCE)
elseif(NOT CMAKE_SYSTEM_NAME MATCHES "^(FreeBSD|OpenBSD)$")
    list(APPEND LIBRDP_SYSTEM_COMPILE_DEFINITIONS _POSIX_C_SOURCE=200809L)
endif()

function(librdp_apply_system_definitions target)
    if(LIBRDP_SYSTEM_COMPILE_DEFINITIONS)
        target_compile_definitions(${target} PRIVATE ${LIBRDP_SYSTEM_COMPILE_DEFINITIONS})
    endif()
endfunction()

set(LIBRDP_OPTION_VALUES AUTO ON OFF)

function(librdp_feature_option name description)
    set(${name} "AUTO" CACHE STRING "${description} (AUTO, ON, OFF)")
    set_property(CACHE ${name} PROPERTY STRINGS ${LIBRDP_OPTION_VALUES})
    string(TOUPPER "${${name}}" value)
    list(FIND LIBRDP_OPTION_VALUES "${value}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "${name} must be AUTO, ON, or OFF")
    endif()
    if(NOT "${${name}}" STREQUAL "${value}")
        set(${name} "${value}" CACHE STRING "${description} (AUTO, ON, OFF)" FORCE)
    endif()
endfunction()

function(librdp_pkg_dependency option prefix)
    set(${prefix}_FOUND 0 PARENT_SCOPE)
    if("${${option}}" STREQUAL "OFF")
        return()
    endif()
    if(NOT PkgConfig_FOUND)
        if("${${option}}" STREQUAL "ON")
            message(FATAL_ERROR "${option}=ON requires pkg-config")
        endif()
        return()
    endif()
    if("${${option}}" STREQUAL "ON")
        pkg_check_modules(${prefix} REQUIRED IMPORTED_TARGET ${ARGN})
    else()
        pkg_check_modules(${prefix} QUIET IMPORTED_TARGET ${ARGN})
    endif()
    set(${prefix}_FOUND "${${prefix}_FOUND}" PARENT_SCOPE)
endfunction()

function(librdp_summary_line name requested dependency target_name compiled reason)
    message(STATUS "librdp feature name=${name} requested=${requested} dependency=${dependency} target=${target_name} compiled=${compiled} reason=${reason}")
endfunction()

function(librdp_summary_build_target name option target_name)
    if(${option})
        librdp_summary_line(${name} ON not-applicable ${target_name} yes enabled)
    else()
        librdp_summary_line(${name} OFF not-applicable ${target_name} no disabled-by-user)
    endif()
endfunction()

function(librdp_summary_optional_backend name option found target_name)
    if("${${option}}" STREQUAL "OFF")
        librdp_summary_line(${name} "${${option}}" not-searched "${target_name}" no disabled-by-user)
    elseif(${found})
        librdp_summary_line(${name} "${${option}}" found "${target_name}" yes enabled)
    else()
        set(reason dependency-not-found)
        if(DEFINED ${found}_REASON AND NOT "${${found}_REASON}" STREQUAL "")
            set(reason "${${found}_REASON}")
        endif()
        librdp_summary_line(${name} "${${option}}" missing "${target_name}" no ${reason})
    endif()
endfunction()

function(librdp_summary_viewer_backend name option found)
    if("${${option}}" STREQUAL "OFF")
        librdp_summary_line(${name} "${${option}}" not-searched librdp-x11-viewer no disabled-by-user)
    elseif(NOT LIBRDP_BUILD_X11_VIEWER)
        if(${found})
            set(dependency found)
        else()
            set(dependency missing)
        endif()
        librdp_summary_line(${name} "${${option}}" ${dependency} librdp-x11-viewer no parent-target-disabled)
    elseif(${found})
        librdp_summary_line(${name} "${${option}}" found librdp-x11-viewer yes enabled)
    else()
        librdp_summary_line(${name} "${${option}}" missing librdp-x11-viewer no dependency-not-found)
    endif()
endfunction()

librdp_feature_option(LIBRDP_WITH_FFMPEG_AVC "Use FFmpeg for AVC decoding")
librdp_feature_option(LIBRDP_WITH_OPENH264_AVC "Use OpenH264 for AVC decoding")
librdp_feature_option(LIBRDP_WITH_PCSC "Use PC/SC smartcard backend")
librdp_feature_option(LIBRDP_WITH_LIBUSB "Use libusb device backend")
librdp_feature_option(LIBRDP_WITH_FIDO2 "Use FIDO2 authenticator backend")
librdp_feature_option(LIBRDP_WITH_CBOR "Use CBOR helpers for WebAuthn data")
librdp_feature_option(LIBRDP_WITH_CUPS "Use CUPS printer backend")
librdp_feature_option(LIBRDP_WITH_ACL "Use POSIX ACL filesystem metadata backend")
librdp_feature_option(LIBRDP_WITH_ATTR "Use extended attribute filesystem metadata backend")
librdp_feature_option(LIBRDP_WITH_ARCHIVE "Use archive-backed print payload support")
librdp_feature_option(LIBRDP_WITH_CURL "Use libcurl for HTTP transport backends")
librdp_feature_option(LIBRDP_WITH_LIBXML2 "Use libxml2 for workspace feed parsing")
librdp_feature_option(LIBRDP_WITH_PIPEWIRE "Use PipeWire audio backend in the X11 viewer")
librdp_feature_option(LIBRDP_WITH_JPEG "Use JPEG camera conversion backend in the X11 viewer")
librdp_feature_option(LIBRDP_WITH_XSHM "Use MIT-SHM presentation path in the X11 viewer")
librdp_feature_option(LIBRDP_WITH_XRANDR "Use XRandR monitor layout bridge in the X11 viewer")
