# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

set(CPACK_PACKAGE_NAME "librdp")
set(CPACK_PACKAGE_VENDOR "Marco Fortina")
set(CPACK_PACKAGE_CONTACT "Marco Fortina <marco_fortina@hotmail.it>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "RDP client library and optional X11 viewer")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/marcofortina/librdp")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_GENERATOR TGZ)

find_program(LIBRDP_DPKG_DEB_EXECUTABLE dpkg-deb)
if(LIBRDP_DPKG_DEB_EXECUTABLE)
    list(APPEND CPACK_GENERATOR DEB)
    set(CPACK_DEBIAN_PACKAGE_NAME "librdp")
    set(CPACK_DEBIAN_PACKAGE_SECTION "libs")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Marco Fortina <marco_fortina@hotmail.it>")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
endif()

find_program(LIBRDP_RPMBUILD_EXECUTABLE rpmbuild)
if(LIBRDP_RPMBUILD_EXECUTABLE)
    list(APPEND CPACK_GENERATOR RPM)
    set(CPACK_RPM_PACKAGE_NAME "librdp")
    set(CPACK_RPM_PACKAGE_GROUP "System/Libraries")
    set(CPACK_RPM_PACKAGE_LICENSE "AGPL-3.0-or-later")
    set(CPACK_RPM_PACKAGE_RELEASE "1")
endif()

if(APPLE)
    find_program(LIBRDP_PRODUCTBUILD_EXECUTABLE productbuild)
    if(LIBRDP_PRODUCTBUILD_EXECUTABLE)
        list(APPEND CPACK_GENERATOR productbuild)
        set(CPACK_PRODUCTBUILD_IDENTIFIER "org.marcofortina.librdp")
    endif()
endif()
include(CPack)
