# Copyright (C) 2026 Marco Fortina
# SPDX-License-Identifier: AGPL-3.0-or-later

message(STATUS "librdp feature summary begin")
string(REPLACE ";" "+" LIBRDP_LIBRARY_TARGETS_SUMMARY "${LIBRDP_LIBRARY_TARGETS}")
librdp_summary_line(library "${LIBRDP_LIBRARY_TYPE}" not-applicable "${LIBRDP_LIBRARY_TARGETS_SUMMARY}" yes "primary-${LIBRDP_PRIMARY_LIBRARY_KIND}")
if(LIBRDP_ENABLE_WERROR)
    librdp_summary_line(werror ON not-applicable project-targets yes enabled)
else()
    librdp_summary_line(werror OFF not-applicable project-targets no disabled-by-user)
endif()
if(LIBRDP_ENABLE_SANITIZERS)
    librdp_summary_line(sanitizers ON not-applicable project-targets yes "${LIBRDP_SANITIZER_FLAG_VALUE}")
else()
    librdp_summary_line(sanitizers OFF not-applicable project-targets no disabled-by-user)
endif()
librdp_summary_build_target(tests LIBRDP_BUILD_TESTS librdp_tests)
librdp_summary_build_target(examples LIBRDP_BUILD_EXAMPLES examples)
librdp_summary_build_target(fuzz LIBRDP_BUILD_FUZZ fuzz-targets)
if(LIBRDP_BUILD_X11_VIEWER)
    librdp_summary_line(x11-viewer ON found librdp-x11-viewer yes enabled)
else()
    librdp_summary_line(x11-viewer OFF not-searched librdp-x11-viewer no disabled-by-user)
endif()
if(DOXYGEN_FOUND)
    librdp_summary_line(docs-api AUTO found docs-api yes enabled)
else()
    librdp_summary_line(docs-api AUTO missing docs-api no dependency-not-found)
endif()
if(LIBRDP_BUILD_X11_VIEWER)
    set(LIBRDP_DEVICE_BACKEND_TARGETS librdp+librdp-x11-viewer)
else()
    set(LIBRDP_DEVICE_BACKEND_TARGETS librdp)
endif()
librdp_summary_optional_backend(ffmpeg-avc LIBRDP_WITH_FFMPEG_AVC LIBRDP_FFMPEG_AVC_FOUND librdp)
librdp_summary_optional_backend(openh264-avc LIBRDP_WITH_OPENH264_AVC LIBRDP_OPENH264_AVC_FOUND librdp)
librdp_summary_optional_backend(pcsc LIBRDP_WITH_PCSC LIBRDP_PCSC_FOUND "${LIBRDP_DEVICE_BACKEND_TARGETS}")
librdp_summary_optional_backend(libusb LIBRDP_WITH_LIBUSB LIBRDP_LIBUSB_FOUND "${LIBRDP_DEVICE_BACKEND_TARGETS}")
librdp_summary_optional_backend(fido2 LIBRDP_WITH_FIDO2 LIBRDP_FIDO2_FOUND "${LIBRDP_DEVICE_BACKEND_TARGETS}")
librdp_summary_optional_backend(cbor LIBRDP_WITH_CBOR LIBRDP_CBOR_FOUND librdp)
librdp_summary_optional_backend(cups LIBRDP_WITH_CUPS LIBRDP_CUPS_FOUND librdp_backend_objects)
librdp_summary_optional_backend(acl LIBRDP_WITH_ACL LIBRDP_ACL_FOUND librdp)
librdp_summary_optional_backend(attr LIBRDP_WITH_ATTR LIBRDP_ATTR_FOUND librdp)
librdp_summary_optional_backend(archive LIBRDP_WITH_ARCHIVE LIBRDP_ARCHIVE_FOUND librdp)
librdp_summary_optional_backend(curl LIBRDP_WITH_CURL LIBRDP_CURL_FOUND librdp)
librdp_summary_viewer_backend(pipewire LIBRDP_WITH_PIPEWIRE LIBRDP_PIPEWIRE_FOUND)
librdp_summary_viewer_backend(jpeg LIBRDP_WITH_JPEG LIBRDP_JPEG_FOUND)
librdp_summary_viewer_backend(xshm LIBRDP_WITH_XSHM LIBRDP_XSHM_FOUND)
librdp_summary_viewer_backend(xrandr LIBRDP_WITH_XRANDR LIBRDP_XRANDR_FOUND)
message(STATUS "librdp feature summary end")
